### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by HuntrRose** [HuntrRose/TGW#1]
-  [x] Add attack and damage algorithm`*
-  [ ] Add ArtilleryUnit class
-  [ ] Add graphics for Artillery and Infantry for both players
- [ ] Add graphics for Armored Car for second player
- [ ] Fix Unit to graphics converter to incorporate player
- [ ] Make End turn button more visible
- [ ] Display info on selected unit
- [ ] Display info on potential target when hovering
- [ ] implement end of game

**Comment by HuntrRose** [comment]
attack and damage created. Needs tuning.
Also End of Game needs to be implemented
